### ISSUE TITLE
Error Coming Whille running callable example

### ISSUE THREAD

**Issue by raina070** [gridgain/gridgain#100]
I tried to run the following code for ComputeCallable

 Ignite ignite = Ignition.start("config/ignite-config.xml");

 System.out.println(">>> Compute callable example started.");

        Collection<IgniteCallable<Integer>> calls = new ArrayList<IgniteCallable<Integer>>();

        // Iterate through all words in the sentence and create callable jobs.
        for (final String word : "Count characters using callable".split(" ")) {
            calls.add(new IgniteCallable<Integer>() {
                public Integer call() throws Exception {
                    System.out.println();
                    System.out.println(">>> Printing '" + word + "' on this node from ignite job.");

                    return word.length();
                }
            });
        }

        // Execute collection of callables on the ignite.
       Collection<Integer> res = ignite.compute().call(calls);

        int sum = 0;

        // Add up individual word lengths received from remote nodes.
        for (int len : res)
            sum += len;

        System.out.println();
        System.out.println(">>> Total number of characters in the phrase is '" + sum + "'.");
        System.out.println(">>> Check all nodes for output (this node is also part of the cluster).");

I got the following error on running this

[13:45:31] ver. 1.5.0-final#20151229-sha1:f1f8cda2
[13:45:31] 2015 Copyright(C) Apache Software Foundation
[13:45:31] 
[13:45:31] Ignite documentation: http://ignite.apache.org
[13:45:31] 
[13:45:31] Quiet mode.
[13:45:31]   ^-- Logging to file '\work\log\ignite-e40e4552.log'
[13:45:31]   ^-- To see **FULL** console log here add -DIGNITE_QUIET=false or "-v" to ignite.{sh|bat}
[13:45:31] 
[13:45:31] OS: Windows 7 6.1 x86
[13:45:31] VM information: Java(TM) SE Runtime Environment 1.8.0_74-b31 Oracle Corporation Java HotSpot(TM) Client VM 25.74-b31
[13:45:31] Initial heap size is 16MB (should be no less than 512MB, use -Xms512m -Xmx512m).
[13:45:32] Configured plugins:
[13:45:32]   ^-- None
[13:45:32] 
[13:45:33] Security status [authentication=off, tls/ssl=off]
[13:45:35] Performance suggestions for grid  (fix if possible)
[13:45:35] To disable, set -DIGNITE_PERFORMANCE_SUGGESTIONS_DISABLED=true
[13:45:35]   ^-- Disable peer class loading (set 'peerClassLoadingEnabled' to false)
[13:45:35]   ^-- Disable grid events (remove 'includeEventTypes' from configuration)
[13:45:35] 
[13:45:35] To start Console Management & Monitoring run ignitevisorcmd.{sh|bat}
[13:45:35] 
[13:45:35] Ignite node started OK (id=e40e4552)
[13:45:35] Topology snapshot [ver=6, servers=6, clients=0, CPUs=2, heap=1.5GB]
>>> Compute callable example started.

[13:45:35,214][ERROR][sys-#25%null%][GridTaskWorker] Failed to obtain remote job result policy for result from ComputeTask.result(..) method (will fail the whole task): GridJobResultImpl [job=C2 [], sib=GridJobSiblingImpl [sesId=1c93bc88351-e40e4552-3962-4877-96ab-4b57270e40c8, jobId=6c93bc88351-97d85c4f-2941-4e7e-8ac4-b2fec2cc3826, nodeId=97d85c4f-2941-4e7e-8ac4-b2fec2cc3826, isJobDone=false], jobCtx=GridJobContextImpl [jobId=6c93bc88351-97d85c4f-2941-4e7e-8ac4-b2fec2cc3826, timeoutObj=null, attrs={}], node=TcpDiscoveryNode [id=97d85c4f-2941-4e7e-8ac4-b2fec2cc3826, addrs=[0:0:0:0:0:0:0:1, 10.224.143.207, 127.0.0.1], sockAddrs=[PC213863.cts.com/10.224.143.207:47500, /0:0:0:0:0:0:0:1:47500, /10.224.143.207:47500, /127.0.0.1:47500], discPort=47500, order=1, intOrder=1, lastExchangeTime=1458288934280, loc=false, ver=1.5.0#20151229-sha1:f1f8cda2, isClient=false], ex=class o.a.i.compute.ComputeUserUndeclaredException: Failed to execute job due to unexpected runtime exception [jobId=6c93bc88351-97d85c4f-2941-4e7e-8ac4-b2fec2cc3826, ses=GridJobSessionImpl [ses=GridTaskSessionImpl [taskName=com.ing.ignite.IgnitionNodeStartUp$1, dep=GridDeployment [ts=1458287647945, depMode=SHARED, clsLdr=sun.misc.Launcher$AppClassLoader@1d16e93, clsLdrId=86077b88351-97d85c4f-2941-4e7e-8ac4-b2fec2cc3826, userVer=0, loc=true, sampleClsName=com.ing.ignite.IgnitionNodeStartUp$1, pendingUndeploy=false, undeployed=false, usage=1], taskClsName=com.ing.ignite.IgnitionNodeStartUp$1, sesId=1c93bc88351-e40e4552-3962-4877-96ab-4b57270e40c8, startTime=1458288935144, endTime=9223372036854775807, taskNodeId=e40e4552-3962-4877-96ab-4b57270e40c8, clsLdr=sun.misc.Launcher$AppClassLoader@1d16e93, closed=false, cpSpi=null, failSpi=null, loadSpi=null, usage=1, fullSup=false, subjId=e40e4552-3962-4877-96ab-4b57270e40c8, mapFut=IgniteFuture [orig=GridFutureAdapter [resFlag=0, res=null, startTime=1458288935186, endTime=0, ignoreInterrupts=false, lsnr=null, state=INIT]]], jobId=6c93bc88351-97d85c4f-2941-4e7e-8ac4-b2fec2cc3826]], hasRes=true, isCancelled=false, isOccupied=true]
class org.apache.ignite.IgniteException: Remote job threw user exception (override or implement ComputeTask.result(..) method if you would like to have automatic failover for this exception).
	at org.apache.ignite.compute.ComputeTaskAdapter.result(ComputeTaskAdapter.java:101)
	at org.apache.ignite.internal.processors.task.GridTaskWorker$3.apply(GridTaskWorker.java:909)
	at org.apache.ignite.internal.processors.task.GridTaskWorker$3.apply(GridTaskWorker.java:902)
	at org.apache.ignite.internal.util.IgniteUtils.wrapThreadLoader(IgniteUtils.java:6429)
	at org.apache.ignite.internal.processors.task.GridTaskWorker.result(GridTaskWorker.java:902)
	at org.apache.ignite.internal.processors.task.GridTaskWorker.onResponse(GridTaskWorker.java:798)
	at org.apache.ignite.internal.processors.task.GridTaskProcessor.processJobExecuteResponse(GridTaskProcessor.java:995)
	at org.apache.ignite.internal.processors.task.GridTaskProcessor$JobMessageListener.onMessage(GridTaskProcessor.java:1219)
	at org.apache.ignite.internal.managers.communication.GridIoManager.processRegularMessage0(GridIoManager.java:821)
	at org.apache.ignite.internal.managers.communication.GridIoManager.access$1600(GridIoManager.java:103)
	at org.apache.ignite.internal.managers.communication.GridIoManager$5.run(GridIoManager.java:784)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: class org.apache.ignite.compute.ComputeUserUndeclaredException: Failed to execute job due to unexpected runtime exception [jobId=6c93bc88351-97d85c4f-2941-4e7e-8ac4-b2fec2cc3826, ses=GridJobSessionImpl [ses=GridTaskSessionImpl [taskName=com.ing.ignite.IgnitionNodeStartUp$1, dep=GridDeployment [ts=1458287647945, depMode=SHARED, clsLdr=sun.misc.Launcher$AppClassLoader@1d16e93, clsLdrId=86077b88351-97d85c4f-2941-4e7e-8ac4-b2fec2cc3826, userVer=0, loc=true, sampleClsName=com.ing.ignite.IgnitionNodeStartUp$1, pendingUndeploy=false, undeployed=false, usage=1], taskClsName=com.ing.ignite.IgnitionNodeStartUp$1, sesId=1c93bc88351-e40e4552-3962-4877-96ab-4b57270e40c8, startTime=1458288935144, endTime=9223372036854775807, taskNodeId=e40e4552-3962-4877-96ab-4b57270e40c8, clsLdr=sun.misc.Launcher$AppClassLoader@1d16e93, closed=false, cpSpi=null, failSpi=null, loadSpi=null, usage=1, fullSup=false, subjId=e40e4552-3962-4877-96ab-4b57270e40c8, mapFut=IgniteFuture [orig=GridFutureAdapter [resFlag=0, res=null, startTime=1458288935186, endTime=0, ignoreInterrupts=false, lsnr=null, state=INIT]]], jobId=6c93bc88351-97d85c4f-2941-4e7e-8ac4-b2fec2cc3826]]
	at org.apache.ignite.internal.processors.job.GridJobWorker.handleThrowable(GridJobWorker.java:607)
	at org.apache.ignite.internal.processors.job.GridJobWorker.initialize(GridJobWorker.java:427)
	at org.apache.ignite.internal.processors.job.GridJobProcessor.processJobExecuteRequest(GridJobProcessor.java:1094)
	at org.apache.ignite.internal.processors.job.GridJobProcessor$JobExecutionListener.onMessage(GridJobProcessor.java:1770)
	... 6 more
Caused by: java.lang.ClassCastException: com.ing.ignite.IgnitionNodeStartUp$1 cannot be cast to java.util.concurrent.Callable
	at org.apache.ignite.internal.processors.closure.GridClosureProcessor$C2.readExternal(GridClosureProcessor.java:1808)
	at org.apache.ignite.marshaller.optimized.OptimizedObjectInputStream.readExternalizable(OptimizedObjectInputStream.java:514)
	at org.apache.ignite.marshaller.optimized.OptimizedClassDescriptor.read(OptimizedClassDescriptor.java:803)
	at org.apache.ignite.marshaller.optimized.OptimizedObjectInputStream.readObjectOverride(OptimizedObjectInputStream.java:315)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:365)
	at org.apache.ignite.marshaller.optimized.OptimizedMarshaller.unmarshal(OptimizedMarshaller.java:219)
	at org.apache.ignite.internal.binary.BinaryUtils.doReadOptimized(BinaryUtils.java:1470)
	at org.apache.ignite.internal.binary.BinaryReaderExImpl.deserialize(BinaryReaderExImpl.java:1627)
	at org.apache.ignite.internal.binary.GridBinaryMarshaller.deserialize(GridBinaryMarshaller.java:292)
	at org.apache.ignite.internal.binary.BinaryMarshaller.unmarshal(BinaryMarshaller.java:112)
	at org.apache.ignite.internal.processors.job.GridJobWorker.initialize(GridJobWorker.java:409)
	... 8 more
Exception in thread "main" class org.apache.ignite.IgniteException: com.ing.ignite.IgnitionNodeStartUp$1 cannot be cast to java.util.concurrent.Callable
	at org.apache.ignite.internal.util.IgniteUtils.convertException(IgniteUtils.java:882)
	at org.apache.ignite.internal.IgniteComputeImpl.call(IgniteComputeImpl.java:372)
	at com.ing.ignite.IgnitionNodeStartUp.main(IgnitionNodeStartUp.java:60)
Caused by: class org.apache.ignite.IgniteCheckedException: com.ing.ignite.IgnitionNodeStartUp$1 cannot be cast to java.util.concurrent.Callable
	at org.apache.ignite.internal.util.IgniteUtils.cast(IgniteUtils.java:7005)
	at org.apache.ignite.internal.util.future.GridFutureAdapter.get0(GridFutureAdapter.java:166)
	at org.apache.ignite.internal.util.future.GridFutureAdapter.get(GridFutureAdapter.java:115)
	at org.apache.ignite.internal.AsyncSupportAdapter.saveOrGet(AsyncSupportAdapter.java:112)
	at org.apache.ignite.internal.IgniteComputeImpl.call(IgniteComputeImpl.java:369)
	... 1 more
Caused by: java.lang.ClassCastException: com.ing.ignite.IgnitionNodeStartUp$1 cannot be cast to java.util.concurrent.Callable
	at org.apache.ignite.internal.processors.closure.GridClosureProcessor$C2.readExternal(GridClosureProcessor.java:1808)
	at org.apache.ignite.marshaller.optimized.OptimizedObjectInputStream.readExternalizable(OptimizedObjectInputStream.java:514)
	at org.apache.ignite.marshaller.optimized.OptimizedClassDescriptor.read(OptimizedClassDescriptor.java:803)
	at org.apache.ignite.marshaller.optimized.OptimizedObjectInputStream.readObjectOverride(OptimizedObjectInputStream.java:315)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:365)
	at org.apache.ignite.marshaller.optimized.OptimizedMarshaller.unmarshal(OptimizedMarshaller.java:219)
	at org.apache.ignite.internal.binary.BinaryUtils.doReadOptimized(BinaryUtils.java:1470)
	at org.apache.ignite.internal.binary.BinaryReaderExImpl.deserialize(BinaryReaderExImpl.java:1627)
	at org.apache.ignite.internal.binary.GridBinaryMarshaller.deserialize(GridBinaryMarshaller.java:292)
	at org.apache.ignite.internal.binary.BinaryMarshaller.unmarshal(BinaryMarshaller.java:112)
	at org.apache.ignite.internal.processors.job.GridJobWorker.initialize(GridJobWorker.java:409)
	at org.apache.ignite.internal.processors.job.GridJobProcessor.processJobExecuteRequest(GridJobProcessor.java:1094)
	at org.apache.ignite.internal.processors.job.GridJobProcessor$JobExecutionListener.onMessage(GridJobProcessor.java:1770)
	at org.apache.ignite.internal.managers.communication.GridIoManager.processRegularMessage0(GridIoManager.java:821)
	at org.apache.ignite.internal.managers.communication.GridIoManager.access$1600(GridIoManager.java:103)
	at org.apache.ignite.internal.managers.communication.GridIoManager$5.run(GridIoManager.java:784)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

could you please let me know the reason of the error?

**Comment by raina070** [comment]
Started 2 JVMs and the issue was resolved
