### ISSUE TITLE
Do not support "Secondary Hadoop FS URI"

### ISSUE THREAD

**Issue by qinxinwei** [gridgain/gridgain#94]
Hi, all
Under the guidance of http://hadoop.gridgain.org/latest/Configuration, I add the following configuration items into default-config.xml to set DUAL_ASYNC mode and use  Apache HDFS as my secondary file system:

		
        <property name="defaultMode" value="DUAL_ASYNC"/>
		
		
        <property name="secondaryHadoopFileSystemUri" value="hdfs://9.91.11.163:9000"/>

        
        <property name="secondaryHadoopFileSystemConfigPath" value="/home/qxw/hadoop/hadoop-2.6.0/etc/hadoop/core-site.xml"/>

But  there is following error when I run bin/ggstart.sh:

class org.gridgain.grid.GridException: Failed to instantiate Spring XML application context [springUrl=file:/home/qxw/gridgain/gridgain-hadoop-os-6.6.2/config/default-config.xml, err=Error creating bean with name 'grid.cfg' defined in URL [file:/home/qxw/gridgain/gridgain-hadoop-os-6.6.2/config/default-config.xml]: Cannot create inner bean 'org.gridgain.grid.ggfs.GridGgfsConfiguration#1602c861' of type [org.gridgain.grid.ggfs.GridGgfsConfiguration] while setting bean property 'ggfsConfiguration' with key [0]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.gridgain.grid.ggfs.GridGgfsConfiguration#1602c861' defined in URL [file:/home/qxw/gridgain/gridgain-hadoop-os-6.6.2/config/default-config.xml]: Error setting property values; nested exception is org.springframework.beans.NotWritablePropertyException: Invalid property 'secondaryHadoopFileSystemUri' of bean class [org.gridgain.grid.ggfs.GridGgfsConfiguration]: Bean property 'secondaryHadoopFileSystemUri' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?]
For more information see:
    Troubleshooting:      http://bit.ly/GridGain-Troubleshooting
    Documentation Center: http://bit.ly/GridGain-Documentation

        at org.gridgain.grid.kernal.processors.spring.GridSpringProcessorImpl.loadConfigurations(GridSpringProcessorImpl.java:98)
        at org.gridgain.grid.kernal.GridGainEx.loadConfigurations(GridGainEx.java:560)
        at org.gridgain.grid.kernal.GridGainEx.start(GridGainEx.java:742)
        at org.gridgain.grid.kernal.GridGainEx.start(GridGainEx.java:709)
        at org.gridgain.grid.kernal.GridGainEx.start(GridGainEx.java:663)
        at org.gridgain.grid.kernal.GridGainEx.start(GridGainEx.java:523)
        at org.gridgain.grid.kernal.GridGainEx.start(GridGainEx.java:493)
        at org.gridgain.grid.GridGain.start(GridGain.java:314)
        at org.gridgain.grid.startup.cmdline.GridCommandLineStartup.main(GridCommandLineStartup.java:293)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'grid.cfg' defined in URL [file:/home/qxw/gridgain/gridgain-hadoop-os-6.6.2/config/default-config.xml]

The execption shows Bean property 'secondaryHadoopFileSystemUri' is not writable or has an invalid setter method, and I don't find  "secondaryHadoopFileSystemUri" field and relevant method in GridGgfsConfiguration.java.

The gridgain version I used is gridgain-hadoop-os-6.6.2.

So, does "secondaryHadoopFileSystemUri" have been renamed? or, could it be said that the opensource version don't support secondary file system, only support ggfs PRIMARY mode?

Thanks.

**Comment by yzhdanov** [comment]
Open source GridGain is being migrated to Apache Ignite. I close this issue for now. You can track your request here - https://issues.apache.org/jira/browse/IGNITE-179
